sonar.projectKey=hams-backend
sonar.projectName=HAMS Backend
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.language=ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.coverage.exclusions=**/migrations/**
